MOVIES = '''
CREATE TABLE IF NOT EXISTS  Movies (
id INTEGER PRIMARY KEY AUTOINCREMENT,
name VARCHAR(100) NOT NULL,
rating REAL NOT NULL DEFAULT 0 CHECK (rating BETWEEN 0 AND 10)
);
'''
USERS = '''
CREATE TABLE IF NOT EXISTS  User (
id INTEGER PRIMARY KEY AUTOINCREMENT,
email VARCHAR(50) UNIQUE NOT NULL,
password VARCHAR(130) NOT NULL
);
'''

CLIENT = '''
CREATE TABLE IF NOT EXISTS  Client (
id INTEGER PRIMARY KEY AUTOINCREMENT,
user_id INTEGER UNIQUE NOT NULL,
FOREIGN KEY (user_id) REFERENCES User(id)
);
'''

EMPLOYEE = '''
CREATE TABLE IF NOT EXISTS  Empoyee (
id INTEGER PRIMARY KEY AUTOINCREMENT,
user_id INTEGER UNIQUE NOT NULL,
FOREIGN KEY (user_id) REFERENCES User(id)
);
'''

PROJECTIONS = '''
CREATE TABLE IF NOT EXISTS  Projections (
id INTEGER PRIMARY KEY AUTOINCREMENT,
movie_id INTEGER NOT NULL,
type VARCHAR(5),
date VARCHAR(10) NOT NULL,
time VARCHAR(5) NOT NULL,
FOREIGN KEY (movie_id) REFERENCES Movies(id)
);
'''

RESERVATIONS= '''
CREATE TABLE IF NOT EXISTS  Reservations (
id INTEGER PRIMARY KEY AUTOINCREMENT,
user_id INTEGER NOT NULL,
projection_id INTEGER NOT NULL,
row INTEGER NOT NULL CHECK (row BETWEEN 1 AND 10),
col INTEGER NOT NULL CHECK (col BETWEEN 1 AND 10),
FOREIGN KEY (user_id) REFERENCES User(id),
FOREIGN KEY (projection_id) REFERENCES Projection(id)
);
'''